[package]
name = "doggo-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "doggo"
path = "src/main.rs"

[dependencies]
clap.workspace = true
clap_derive.workspace = true
doggo-core.workspace = true
